# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rob Olsthoorn
email: me@robolsthoorn.com
description: > # this means to ignore newlines until "baseurl:"
  Rob Olsthoorn | Developer, Traveler, Learner
baseurl: ""
url: "http://robolsthoorn.com"
github_username: rolstenhouse
linkedin_username: rolstenhouse
instagram_username: rob.olsthoorn
twitter: olsthoorn_rob

self_description: Learner, Hacker, Traveler

# Build settings
markdown: kramdown

# include: ['_projects']

exclude: [node_modules, package-lock.json, scripts]


# Always generate OG images
generate_og_images: true
font_family: "Georgia, serif"

collections:
  projects:
    output: true
    permalink: /projects/:path/
  work:
    output: true
    permalink: /work/:path/
  education:
    output: true
    permalink: /education/:path/
  extracurricular:
    output: true
    permalink: /extracurricular/:path/
  writing:
    output: true
    permalink: /writing/:path/

comfortableLanguages: ["Java", "C++", "JavaScript", "Python"]
